### ISSUE TITLE
Error when BUILD_DIR does not exist yet

### ISSUE THREAD

**Issue by rggjan** [shehzan10/arrayfire-windows-scripts#2]
When following the [instructions](https://github.com/shehzan10/arrayfire-windows-scripts/blob/master/README.md), I get the following error when running `rebuild_arrayfire.bat`:

```
PS C:\workspace> .\rebuild_arrayfire.bat
The system cannot find the path specified.
"Running CUDA CMake Configuration"
"Generating CMAKE"
CMake Error: The source directory "C:/workspace" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
"Running msbuild"
Error: C:/workspace/arrayfire/build is not a directory
Error: C:/workspace/arrayfire/build is not a directory
```

After creating a folder "build" (which is BUILD_DIR in common.bat), it works fine.

This folder should be either created automatically or mentioned in the readme...

**Comment by shehzan10** [comment]
If you do `.\rebuild_arrayfire.bat clean` then it will create the directory. [Code here](https://github.com/shehzan10/arrayfire-windows-scripts/blob/master/rebuild_arrayfire.bat#L18).

This is also in the instructions [here](https://github.com/shehzan10/arrayfire-windows-scripts/blob/master/README.md#rebuild_arrayfirebat).

**Comment by rggjan** [comment]
Ah, I didn't see this one. I basically followed the instructions [here](https://github.com/shehzan10/arrayfire-windows-scripts/blob/master/README.md#building-arrayfire) where this is not mentioned:

```
# Using Git Shell
cd C:\workspace
git clone --recursive -b devel https://github.com/arrayfire/arrayfire.git arrayfire
git clone https://github.com/shehzan10/arrayfire-windows-scripts.git scripts
wget http://ci.arrayfire.org/userContent/arrayfire_deps.zip
unzip arrayfire_deps.zip
cp -r scripts\*.bat .\
.\rebuild_arrayfire.bat
```

**Comment by shehzan10** [comment]
Right. I'll update that one. Thanks
