### ISSUE TITLE
VS2015+CUDA8 build fails

### ISSUE THREAD

**Issue by grzegorz-gutowski** [shehzan10/arrayfire-windows-scripts#3]
I'm trying to build the current head of arrayfire using VS2015 and CUDA8. It seems that CPU backend (using MKL) is builded fine, but CUDA backend compilation fails with:

Project "C:\workspace\arrayfire\build\src\backend\cuda\afcuda.vcxproj" (15) is building "C:\workspace\arrayfire\build\src\backend\cuda\cuda_ptx_headers_bin_target.vcxproj
InitializeBuildStatus:
  Touching "x64\Release\cuda_ptx_headers_bin_target\cuda_ptx.8B5A1B81.tlog\unsuccessfulbuild".
CustomBuild:
  Building Custom Rule C:/workspace/arrayfire/src/backend/cuda/CMakeLists.txt
  CMake does not need to re-run because C:\workspace\arrayfire\build\src\backend\cuda\CMakeFiles\generate.stamp is up-to-date.
  Generating arith.ptx
  Error copying file "C:/workspace/arrayfire/build/src/backend/cuda/cuda_compile_ptx_generated_arith.cu.ptx" to "C:/workspace/arrayfire/build/src/backend/cuda/arith.ptx".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\workspace\arrayfire\build\src\
Done Building Project "C:\workspace\arrayfire\build\src\backend\cuda\cuda_ptx_headers_bin_target.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\workspace\arrayfire\build\src\backend\cuda\afcuda.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\workspace\arrayfire\build\src\api\unified\af.vcxproj" (default targets) -- FAILED.

The cuda_compile_ptx_generated_arith.cu.ptx file is not there. Any hints?

**Comment by shehzan10** [comment]
This is related to https://github.com/arrayfire/arrayfire/issues/1688. I'm closing this issue so that it can be discussed on the main arrayfire repository.
